[package]
name = "the_last_of_red"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
static_init = "1.0.1"
bitmask-enum = "1.1.2"